Vote/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vote.DAO;

namespace Vote.Controllers
{
    [Authorize]
    public class FuncionariosController : BaseController
    {
        internal override void CarregarViewBag()
        {
            ViewBag.Disabled = UsuarioAdministrador() ? "" : " disabled";
        }

        // GET: Funcionarios
        public ActionResult Index()
        {
            CarregarViewBag();
            return View(db.Funcionarios.OrderBy(f=>f.Nome).ToList());
        }

        // GET: Funcionarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public ActionResult Create()
        {
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View();
            }
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ativo,Nome,Username,Administrador")] Funcionario funcionario)
        {
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View(funcionario);
            }
            if (ModelState.IsValid)
            {
                db.Funcionarios.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View(funcionario);
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ativo,Nome,Username,Administrador")] Funcionario funcionario)
        {
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View(funcionario);
            }
            if (ModelState.IsValid)
            {
                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View(funcionario);
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (!UsuarioAdministrador())
            {
                ModelState.AddModelError("", "Usuário não possui permissão.");
                return View(funcionario);
            }
            funcionario.Ativo = false;
            db.Entry(funcionario).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Vote/Controllers/VotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vote.DAO;
using Vote.Models;
using Vote.Roles;

namespace Vote.Controllers
{
    [Authorize]
    public class VotosController : BaseController
    {
        internal override void CarregarViewBag()
        {
            ViewBag.IdRestaurante = new SelectList(db.Restaurantes.Where(r=>r.Ativo).OrderBy(r => r.Nome), "Id", "Nome");
        }
     
        // GET: Votos
        public ActionResult Index()
        {
            //ViewBag.Disabled = UsuarioAdministrador() ? "" : " disabled";
            List<VotoViewModel> votos = db.Votos.Include(v => v.Restaurante).OrderByDescending(v=>v.DataVoto).Select(v=> new VotoViewModel() { DataVoto  = v.DataVoto,Restaurante = v.Restaurante, Id = v.Id}).ToList();
            return View(votos);
        }

        // GET: Votos/Create
        public ActionResult Create()
        {
            CarregarViewBag();
            return View();
        }

        // POST: Votos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdRestaurante")] Voto voto)
        {
            if (ModelState.IsValid)
            {
                var funcionario = FuncionarioRoles.ValidaFuncionario(db, UsuarioAtual.Username);
                string resultado = VoteRoles.Votar(db, funcionario.Id, voto.IdRestaurante, DateTimeNow);

                ModelState.AddModelError("",resultado);
                CarregarViewBag();
                return View(voto);
            }

            CarregarViewBag();
            return View(voto);
        }


        // GET: Votos/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Voto voto = db.Votos.Find(id);
        //    if (voto == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(voto);
        //}
        // GET: Votos/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Voto voto = db.Votos.Find(id);
        //    if (voto == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    CarregarViewBag();
        //    if (!UsuarioAdministrador())
        //    {
        //        ModelState.AddModelError("", "Usuário não possui permissão.");
        //        return View(voto);
        //    }

        //    return View(voto);
        //}

        // POST: Votos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,IdRestaurante,IdFuncionario,DataVoto")] Voto voto)
        //{
        //    if (!UsuarioAdministrador())
        //    {
        //        ModelState.AddModelError("", "Usuário não possui permissão.");
        //        return View(voto);
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        if (!UsuarioAdministrador())
        //        {
        //            ModelState.AddModelError("", "Usuário não possui permissão.");
        //            CarregarViewBag();
        //            return View(voto);
        //        }
        //        db.Entry(voto).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(voto);
        //}

        // GET: Votos/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Voto voto = db.Votos.Find(id);
        //    if (voto == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    CarregarViewBag();

        //    if (!UsuarioAdministrador())
        //    {
        //        ModelState.AddModelError("", "Usuário não possui permissão.");
        //        return View(voto);
        //    }
        //    return View(voto);
        //}

        // POST: Votos/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{

        //    Voto voto = db.Votos.Find(id);
        //    if (!UsuarioAdministrador())
        //    {
        //        ModelState.AddModelError("", "Usuário não possui permissão.");
        //        CarregarViewBag();
        //        return View(voto);
        //    }
        //    db.Votos.Remove(voto);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

    }
}

Vote/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="container-fluid">
    <nav class="navbar-expand-lg navbar-light bg-light" role="navigation">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <span class="navbar-brand align-middle">
                @Html.ActionLink(" Vote!", "Index", "Home", new {area = ""}, new {@class = "nav-link fa fa-cutlery"})
            </span>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    @Html.ActionLink("Histórico", "Index", "Votos", new { area = "" }, new { @class = "nav-link" })
                </li>
                @if (Request.IsAuthenticated && Html.UsuarioAdministrador())
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Administração
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            @Html.ActionLink("Categorias", "Index", "Categorias", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Funcionários", "Index", "Funcionarios", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Modalidades", "Index", "Modalidades", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Restaurantes", "Index", "Restaurantes", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container-fluid">
        @if ((ViewBag.Message != null) && (!String.IsNullOrEmpty(ViewBag.Message)))
        {
            <br />
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <i class="fa fa-info-circle"> &nbsp; </i>
                @ViewBag.Message;
            </div>
        }

        @RenderBody()

    </div>
    <footer class="footer">
        <p class="text-muted text-right">&copy; @DateTime.Now.Year - Vote! by Vinicius Costa</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>